apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/madhav-ai-learning/argocd-helm-example.git' # Replace with your repo URL
    path: helm-chart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
